PortfolioItem.create!(image: '/assets/single-1', title: 'Some title', subtitle: 'a little subtitle', category: 'moonwood')
PortfolioItem.create!(image: '/assets/single-2', title: 'Some title', subtitle: 'a little subtitle', category: 'moonwood')
PortfolioItem.create!(image: '/assets/single-3', title: 'Some title', subtitle: 'a little subtitle', category: 'moonwood')
PortfolioItem.create!(image: '/assets/single-4', title: 'Some title', subtitle: 'a little subtitle', category: 'cherry')
PortfolioItem.create!(image: '/assets/single-2', title: 'Some title', subtitle: 'a little subtitle', category: 'cherry')
PortfolioItem.create!(image: '/assets/single-3', title: 'Some title', subtitle: 'a little subtitle', category: 'mahogony')